# -*- coding: utf-8 -*-
"""2_oct_wine classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6ZbAUbvLWqT9yVJqzaR9tjmAoEYOQb4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from sklearn.datasets import load_wine

dataset = load_wine()

dataset

df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

df['target'] = dataset.target

df

df.head()

X = df.iloc[:, 0:13].values

y = df.iloc[:, 13].values

X.shape

y.shape

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

X_train.shape

X_test.shape

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=20)

model.fit(X_train,y_train)

#eval

y_pred = model.predict(X_test)

y_pred

y_test

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

